live

diff --git a/5-odoo.yaml b/5-odoo.yaml
--- a/5-odoo.yaml
+++ b/5-odoo.yaml
@@ -39,6 +39,118 @@ spec:
         resources: {}
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
+      - command:
+        - sh
+        - -c
+        - 'if psql -h db-cbf -U odoo -p 5432 -lqt | cut -d \| -f 1 | grep -qw "cbf";
+          then echo "The database cbf exists." else until createdb -h db-cbf
+          -U odoo -p 5432 cbf; fi '
+        env:
+        - name: POSTGRES_DB
+          value: postgres
+        - name: PGPASSWORD
+          value: odoo
+        - name: POSTGRES_USER
+          value: odoo
+        image: postgres:9.6.5
+        imagePullPolicy: IfNotPresent
+        name: db-install
+        resources: {}
+        terminationMessagePath: /dev/termination-log
+        terminationMessagePolicy: File
+      - command:
+        - sh
+        - -c
+        - |
+          FTP_HOST="ss.vps50988.mylogin.co"
+          FTP_USER="odoo_ss.vps50988.mylogin.co"
+          FTP_PASSWORD="i24125114A"
+          FTP_REMOTE_FILE="dump.sql"
+          FTP_REMOTE_FILESTORE="odoo17-basic.zip"
+          LOCAL_HOST="db-cbf"
+          LOCAL_USER="odoo"
+          LOCAL_DATABASE="cbf"
+          LOCAL_DUMP_FILE="odoo17-basic.zip"
+
+          echo "Entering odoo directory...."
+          cd /mnt/
+          echo "Creating filestore directory..."
+          mkdir filestore
+          mkdir addons
+          echo "Creating $LOCAL_DATABASE directory..."
+          mkdir filestore/$LOCAL_DATABASE
+          echo "Downloading filestore files..."
+          cd addons/
+          wget -P ./ "ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST/$FTP_REMOTE_FILESTORE"
+          echo "Extracting archive..."
+          unzip $LOCAL_DUMP_FILE
+          echo "Move files from directory"
+          mv filestore/* /mnt/filestore/$LOCAL_DATABASE
+          mv dump.sql /mnt/
+          echo "List items in odoo directory..."
+          ls /mnt/
+          echo "List contents in filestore directory..."
+          ls /mnt/filestore/$LOCAL_DATABASE/
+
+          echo "Setting directory permissions..."
+          chmod -Rv 777 /mnt/filestore
+          echo "Permissions set..."
+            
+        #  fi
+        image: busybox
+        imagePullPolicy: IfNotPresent
+        name: filestore-restored
+        volumeMounts:
+        # Edit the volume to match the existing mountPaths in the cluster
+        - mountPath: /mnt
+          name: vol-7xe3r
+          subPath: odoo
+        resources: {}
+        terminationMessagePath: /dev/termination-log
+        terminationMessagePolicy: File
+      - command:
+        - sh
+        - -c
+        - |
+          LOCAL_HOST="db-cbf"
+          LOCAL_USER="odoo"
+          LOCAL_DATABASE="cbf"
+          LOCAL_DUMP_FILE="odoo-basic.dump"
+
+          if ! PGPASSWORD="odoo" psql -h db-cbf -U odoo -d cbf -c "SELECT 1 FROM information_schema.tables WHERE table_name = 'res_users'" | grep -q 1; then
+            echo "The res_users table doesn't exist in the cbf database. Proceeding with database restore..."
+
+            echo "Entering odoo directory..."
+            cd /var/lib/odoo/addons/
+            echo "List contents of odoo directory..."
+            ls /var/lib/odoo/addons/
+
+            echo "Restoring database dump locally..."
+            if PGPASSWORD="odoo" createdb -h "$LOCAL_HOST" -U "$LOCAL_USER" -e "$LOCAL_DATABASE"; then
+              echo "The database $LOCAL_DATABASE created..."
+            else echo "The database $LOCAL_DATABASE already exists..."
+            fi
+            if PGPASSWORD="odoo" pg_restore -h "$LOCAL_HOST" -U "$LOCAL_USER" -d "$LOCAL_DATABASE" -v "$LOCAL_DUMP_FILE"; then
+                 
+                 echo "Database restored successfully."
+                 rm "$LOCAL_DUMP_FILE"
+              else  echo "Database failed to be restored."
+                    rm "$LOCAL_DUMP_FILE"
+              fi
+          else
+            echo "The res_users table already exists in the cbf database. Skipping database restore."
+          fi
+        image: odoo:17
+        imagePullPolicy: IfNotPresent
+        name: db-restored
+        volumeMounts:
+        # Edit the volume to match the existing mountPaths in the cluster
+        - mountPath: /var/lib/odoo
+          name: vol-7xe3r
+          subPath: odoo
+        resources: {}
+        terminationMessagePath: /dev/termination-log
+        terminationMessagePolicy: File
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
@@ -89,7 +201,7 @@ spec:
             port: http
             scheme: HTTP
           initialDelaySeconds: 30
-          periodSeconds: 10
+          periodSeconds: 300
           successThreshold: 1
           timeoutSeconds: 5
         name: odoo-cbf
